name: Java CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['8', '11', '17', '21']

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdk }}

    # Conditional override for javac properties
    - name: Set Javac Override Version
      id: set_javac_version
      run: |
          # If os_version is 21 or 25, set the override property to 1.8
          if [[ "${{ matrix.os_version }}" == "21" || "${{ matrix.os_version }}" == "25" ]]; then
            echo "JAVAC_OVERRIDE=1.8" >> $GITHUB_ENV
          else
            # For 8, 11, and 17, 1.7 will be used.
            echo "JAVAC_OVERRIDE=1.7" >> $GITHUB_ENV
          fi

    # check ant version
    - name: Ant Version
      run: ant -version

    - name: Ant Build (target jars)
      run: ant -noinput -buildfile build.xml -Djavac.source=${{ env.JAVAC_OVERRIDE }} -Djavac.target=${{ env.JAVAC_OVERRIDE }} jars

    - name: Ant Build (target dtdjars)
      run: ant -noinput -buildfile build.xml dtdjars \
          -Djavac.source=${{ env.JAVAC_OVERRIDE }} \
          -Djavac.target=${{ env.JAVAC_OVERRIDE }}

    - name: Ant Test (target ci-test)
      run: ant -noinput -buildfile build.xml clean ci-test \
          -Djavac.source=${{ env.JAVAC_OVERRIDE }} \
          -Djavac.target=${{ env.JAVAC_OVERRIDE }}

    - name: Ant Build (target all)
      run: ant -noinput -buildfile build.xml all \
          -Djavac.source=${{ env.JAVAC_OVERRIDE }} \
          -Djavac.target=${{ env.JAVAC_OVERRIDE }}

    # clean up before running via build script
    - name: Ant Clean
      run: ant -noinput -buildfile build.xml clean

    # The README suggests to use a build script to call ant
    # so we do this as well to make sure it also works this way
    - name: Run build script (target jars)
      run: . ./build.sh jars

    - name: Run build script (target dtdjars)
      run: . ./build.sh dtdjars

    # clean up before running via build script
    # TODO might want to make the clean step a part of build.sh
    - name: Ant Clean
      run: ant -noinput -buildfile build.xml clean

    - name: Run build script (target test)
      run: . ./build.sh test

    # clean up before running via build script
    - name: Ant Clean
      run: ant -noinput -buildfile build.xml clean

    - name: Run build script (target all)
      run: . ./build.sh all
